### ISSUE TITLE
[健身]ATHLEAN-X 学习之翼状肩胛

### ISSUE THREAD

**Issue by mask2012** [mask2012/MaskBlog#26]
## 序
发现youtube上ATHLEAN-X真心不错，官方达到了900多万的订阅量，中文翻译的也是很多，决定把所学所用的感悟记录下来，用输出来增进输入。
安利一下youtube，这个东西如果你还没看过，那你就out了，赶紧跟我来，先买个翻墙的梯子https://github.com/mask2012/MaskBlog/issues/6
另外，如果你不想翻墙，bilibili也是一个替代品，优点是比翻墙快，弹幕评论风景靓丽，缺点是外文资料没有youtube丰富。毕竟他是二手的，很多都是youtube上搬运过来的，你可以称他为油管搬运工。
在某个课题上我会搜集很多资料进行记录，在这里我充当的是kk所说的过滤器的作用，直达有效信息。

## 翼状肩胛
链接 https://www.bilibili.com/video/av10574095?from=search&seid=2610437774313687484
### 翼状肩胛的成因
出现翼状肩的主要原因是，因为前锯肌和斜方肌失去力量或过弱，使肩胛骨失去了贴胸的作用力。当上臂运动使肩胛骨旋转时，它就可以出现因脊柱缘失去牵拉而翘起，形成像翅膀一样形状的畸形

### 翼状肩胛的危害
当我们出现翼状肩胛时，就会使肩部无力、容易疲劳，在上举手臂、推拉重物时肩胛会有不适感，肩、背容易疼痛，关节活动一定程度受限。
- 如果前锯肌损伤较严重，会引发患者胸痛，且在深呼吸时疼痛加重（前锯肌是辅助吸气肌），患者会感觉肋部疼痛；
- 上交叉体态下，前锯肌容易无力，而胸长神经走行于前锯肌之上，可以引起前锯肌表面的筋膜卡压；
- 发生前锯肌筋膜综合征后，患者会反映“气短”或不能深呼吸，在说话时很难一口气讲完一句话；
- 做肩胛骨前伸动作时，疼痛加剧。肩肱节律很容易受到前锯肌损伤的干扰。
- 如果前锯肌不能很好地稳定肩胛骨在胸廓上的位置时，肩胛骨就会乱动，容易造成肩关节撞击综合征。
- 前锯肌短缩和功能降低，很容易使背阔肌过度使用而劳损，还会使斜角肌、胸锁乳突肌等颈部呼吸肌超负荷。因此，如果前锯肌的损伤没有被完全解决，患者的背痛问题就不可能彻底解决。虽然前锯肌损伤也会引起其余颈部辅助呼吸肌的过度收缩，但是膈肌损伤所导致的呼吸代偿更为常见。

### 前锯肌
https://tv.sohu.com/v/dXMvMzE1NjYyNzgxLzg5Mjg5MzI2LnNodG1s.html
这个3d动画很好地展示了前锯肌的分布，知道了这个原理就能想明白怎样才能锻炼到它
同时这个系列的3d动画都特别好，比图展示更容易理解

### 改善方法
第一个方法是臀部固定在墙上，手臂前伸
![1111](https://user-images.githubusercontent.com/6481461/47471783-79edce00-d83e-11e8-96f4-fa33749b71ae.png)

第二个方法
![222222](https://user-images.githubusercontent.com/6481461/47471770-70fcfc80-d83e-11e8-98ee-9be2ceee1fdd.png)

第三个方法是摘苹果
![333333](https://user-images.githubusercontent.com/6481461/47471793-83773600-d83e-11e8-9068-11bb3f9c7176.png)

第四个方法是伏地拉伸
![444444](https://user-images.githubusercontent.com/6481461/47471801-8ffb8e80-d83e-11e8-8593-9030fce8ff36.png)

第五个方法是转墙
![5555555](https://user-images.githubusercontent.com/6481461/47471813-a6094f00-d83e-11e8-8cca-f4f08fee1fd8.png)

### 翼状肩胛扩展阅读
翼状肩胛——害我“驼背”   （这一篇图文讲解深入浅出，还有治疗方法）
https://baijiahao.baidu.com/s?id=1568521450121778&wfr=spider&for=pc

**Comment by beautve** [comment]
你总是如此的优秀

**Comment by mask2012** [comment]
@beautve 优秀毛线啊，我还没练成葵花宝典呢，现在练了三成都不到，看我有生之年能不能练到8成
